config/routes.rb
Rails.application.routes.draw do
  
 

  resources :myplants

  devise_for :users 
  get "signup" => "pages#signup" # creates the flash page sign up page
  root "pages#home" # creates root path to home      
  get "plant_master" => "pages#plant_master" # creates plant_master path
  get "about" => "pages#about" # creates about path
  get "subscribe" => "pages#subscribe" # creates subsribe path

end

app/models/myplant.rb
class Myplant < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, :style => { :medium => "300x300", :thumb => "100x100>"}#, :default_url => "#"   just in case the image fails this will be the default
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"] 
	#validates_something_else # Other validations that conflict with Paperclip's

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :password, :presence => true,
                     :on => :create,
                     :format => {:with => /\A.*(?=.{10,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[\@\#\$\%\^\&\+\=]).*\Z/ }
  has_many :myplants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end

end

app/controllers/myplants_controller.rb
class MyplantsController < ApplicationController
  before_action :set_myplant, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  respond_to :html

  def index
    @myplants = Myplant.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 25)
    respond_with(@myplants)
  end

  def show
    respond_with(@myplant)
  end

  def new
    @myplant = current_user.myplants.build
    respond_with(@myplant)
  end

  def edit
  end

  def create
    @myplant = current_user.myplants.build(myplant_params)
    if @myplant.save
      redirect_to @myplant, notice: 'Your plant was successfully created.'
    else
      render :new
    end
  end

  def update
    if @myplant.update(myplant_params)
      redirect_to @myplant, notice: 'Your plant was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @myplant.destroy
    redirect_to myplant_url
  end

  private
    def set_myplant
      @myplant = Myplant.find(params[:id])
    end

    def correct_user
      @myplant = current_user.myplants.find_by(id: params[:id])
      redirect_to myplants_path, notice: "Not authorized to edit this plant list." if @myplant.nil?
    end

    def myplant_params
      params.require(:myplant).permit(:description, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def signup
	end

	def home
	end

	def myplants
	end

	def plant_master
	end

	def about
	end

	def subscribe
	end
end


app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/myplants_helper.rb
module MyplantsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Plant Website", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Search", root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "My Plants", myplants_path %></li>
        <% end %>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Subscribe", subscribe_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>  
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
			<title>Plantsite</title>
				<meta charset="utf-8">
				<meta name="description" content="AirC&amp;C is the premiere site renting cute cats and canines">
				<meta name="viewport" content="width=device-width, initial-scale=1">
	  		<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,600' rel='stylesheet' type='text/css'>

	  <%= stylesheet_link_tag    'application', media: 'all' %>
	  <%= javascript_include_tag 'application' %>
	  <%= csrf_meta_tags %>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">

 
  

	</head>


	<body>

		<%= render 'layouts/header' %>

		<div class="container"> 
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-info") %>
			<% end %>
			<%= yield %>
		</div>

	</body>

</html>

app/views/myplants/_form.html.erb
<%= form_for @myplant, html: { multpart: true } do |f| %>
  <% if @myplant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@myplant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% @myplant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/myplants/edit.html.erb
<h1>Editing your plant likst</h1>

<%= render 'form' %>

<%= link_to 'Show', @myplant %> |
<%= link_to 'Back', myplants_path %>

app/views/myplants/index.html.erb
<h1>My plants lists</h1>

<div class="box">
    <% if user_signed_in? %>
      <%= link_to new_myplant_path do %>
        <span class="glyphicon glyphicon-plus"></span> 
          New Plant List
      <% end %>
    <% end %>
</div>

<div id="myplants" class="transitions-enabled">
  
    <% @myplants.each do |myplant| %> 
      <div class="box panel panel-default">    
        <%= link_to image_tag(myplant.image.url, width: 300), myplant %>        
        <div class="panel-body">
          <p><%= myplant.description %></p>
          <p><strong><%= myplant.user.name if myplant.user %></strong></p>  
          <% if myplant.user == current_user %>
            <div class="actions">
            <%= link_to edit_myplant_path(myplant) do %>
              <span class="glyphicon glyphicon-edit"></span>
                Edit
            <% end %>
            <%= link_to myplant, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
                Delete
            <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
</div>

<div class="text-center">
   <%= will_paginate @myplants, renderer: BootstrapPagination::Rails %>
</div>

app/views/myplants/new.html.erb
<h1>New plant</h1>

<%= render 'form' %>

<%= link_to 'Back', myplants_path %>

app/views/myplants/show.html.erb
<%= link_to 'Back', myplants_path %>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading center">
			<%= image_tag @myplant.image.url, width: 720 %>
			</div>
			<div class="panel-body">
		<p><%= @myplant.description %></p>
		<p><strong><%= @myplant.user.name if @myplant.user %></strong></p>

		<% if @myplant.user == current_user %>
			<%= link_to edit_myplant_path(@myplant) do %>
        <span class="glyphicon glyphicon-edit"></span>
        Edit
      <% end %>
			<%= link_to @myplant, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <span class="glyphicon glyphicon-trash"></span>
        Delete
      <% end %>
		<% end %>
			</div>
		</div>
	</div>
</div>

app/views/pages/about.html.erb
about this plant website!

app/views/pages/home.html.erb


			<div class="container-center">

				<div class="searchbar">
					<h1>Search Bar</h1>
				</div>

				<div class="searchbutton">
					<%= link_to "Search", "#", class: "btn btn-success btn-lg" %>
				</div>

			</div>





			

app/views/pages/plant_master.html.erb

<body>
	<div class="name">
		<h1>Common Names</h1>
		<p>Scientific Name</p>
	</div>

	<fieldset class="rating">
    <input type="radio" id="star5" name="rating" value="5" />
    <label class = "full" for="star5" title="Amazing"></label>
    <input type="radio" id="star4half" name="rating" value="4 and a half" />
    <label class="half" for="star4half" title="Very nice"></label>
    <input type="radio" id="star4" name="rating" value="4" />
    <label class = "full" for="star4" title="Good"></label>
    <input type="radio" id="star3half" name="rating" value="3 and a half" />
    <label class="half" for="star3half" title="Descent"></label>
    <input type="radio" id="star3" name="rating" value="3" />
    <label class = "full" for="star3" title="Acceptable"></label>
    <input type="radio" id="star2half" name="rating" value="2 and a half" />
    <label class="half" for="star2half" title="Neutral"></label>
    <input type="radio" id="star2" name="rating" value="2" />
    <label class = "full" for="star2" title="Dissapointing"></label>
    <input type="radio" id="star1half" name="rating" value="1 and a half" />
    <label class="half" for="star1half" title="Poor"></label>
    <input type="radio" id="star1" name="rating" value="1" />
    <label class = "full" for="star1" title="Bad"></label>
    <input type="radio" id="starhalf" name="rating" value="half" />
    <label class="half" for="starhalf" title="Terrible"></label>
	</fieldset>



	<div class="hardiness">
		<h1>4-9</h1>
		<p>Hardiness Zone</p>
	</div>


	<!-- Flowers button-->
	
	

<div class="container">
  
  <div class="parts">
    <!--<div class="col-lg-12">-->

     

    <!-- Flowers button-->
        <div class="flower">
        	<div class="flowertitle">	
    				<h1>Flower</h1>				
    			</div>
        	<div class="flowerbutton">
          	<button class="btn btn-default" type="button" data-target="#flowerbutton" data-toggle="modal">
             	<img src="#">
          	</button>
        	</div>
        </div>

  <!-- Fruit button-->
        <div class="fruit">
          <div class="fruittitle">  
            <h1>Fruit</h1>        
          </div>

          <div class="fruitbutton">
            <button class="btn btn-default" type="button" data-target="#fruitbutton" data-toggle="modal">
              <img src="#">
            </button>
          </div>
        </div>

 

    <!-- General button-->
        <div class="general">
          <div class="generaltitle">  
            <h1>General</h1>        
          </div>

          <div class="generalbutton">
            <button class="btn btn-default" type="button" data-target="#generalbutton" data-toggle="modal">
              <img src="#"alt="General">
            </button>
          </div>
        </div>
        
   

      

  <!-- Leaves button-->
        <div class="leaves">
          <div class="leavestitle"> 
            <h1>Leaves</h1>       
          </div>

          <div class="leafbutton">
            <button class="btn btn-default" type="button" data-target="#leafbutton" data-toggle="modal">
              <img src="#">
            </button>
          </div>
        </div>
      

  <!-- Twigs and Stems button-->
        <div class="twigs-stems">
    			<div class="twigs-stemstitle">	
    				<h1>Twigs and Stems</h1>				
    			</div>

        	<div class="twigs-stemsbutton">
          	<button class="btn btn-default" type="button" data-target="#twigs-stemsbutton" data-toggle="modal">
             	<img src="#">
          	</button>
        	</div>
        </div>

      
    <!--</div>-->
  </div>



  <!-- Flower Modal -->
  <div tabindex="-1" class="modal fade" id="flowerbutton" role="dialog" aria-hidden="true" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button class="close" aria-label="Close" type="button" data-dismiss="modal"><span  aria-hidden="true">×</span></button>
          <h4 class="modal-title" id="myModalLabel">Flowers</h4>
          <img src="#">
        </div>
        <div class="modal-body">
          <p>Lorem ipsum dolor sit amet, faucibus libero ac. Purus tincidunt, eros amet eu, mattis ac sed. Tincidunt nibh vestibulum. Non magna, lobortis vestibulum, amet et. Mattis quis tincidunt, ut voluptatem. Non ligula nostra, suscipit in donec.

  				In nisl. Magna magna sem, vel risus, mauris nunc purus. Ante in feugiat, sit phasellus suscipit, in mus facilisis. Tristique atque, erat et pede, lorem faucibus elit. Duis accumsan pulvinar.</p>
        </div>      
      </div>
    </div>
  </div>
    
  <!-- Fruit Modal -->
  <div tabindex="-1" class="modal fade" id="fruitbutton" role="dialog" aria-hidden="true" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button class="close" aria-label="Close" type="button" data-dismiss="modal"><span aria-hidden="true">×</span></button>
          <h4 class="modal-title"id="myModalLabel">Fruit</h4>
          <img src="#">
        </div>
        <div class="modal-body">
  				<p>Lorem ipsum dolor sit amet, faucibus libero ac. Purus tincidunt, eros amet eu, mattis ac sed. Tincidunt nibh vestibulum. Non magna, lobortis vestibulum, amet et. Mattis quis tincidunt, ut voluptatem. Non ligula nostra, suscipit in donec.

  				In nisl. Magna magna sem, vel risus, mauris nunc purus. Ante in feugiat, sit phasellus suscipit, in mus facilisis. Tristique atque, erat et pede, lorem faucibus elit. Duis accumsan pulvinar.</p>
        </div>      
      </div>
    </div>
  </div>

  <!-- Leaves Modal  -->
  <div tabindex="-1" class="modal fade" id="leafbutton" role="dialog" aria-hidden="true" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button class="close" aria-label="Close" type="button" data-dismiss="modal"><span  aria-hidden="true">×</span></button>
          <h4 class="modal-title" id="myModalLabel">Leaves</h4>
          <img src="#">
        </div>
        <div class="modal-body">
          <p>Lorem ipsum dolor sit amet, faucibus libero ac. Purus tincidunt, eros amet eu, mattis ac sed. Tincidunt nibh vestibulum. Non magna, lobortis vestibulum, amet et. Mattis quis tincidunt, ut voluptatem. Non ligula nostra, suscipit in donec.

  				In nisl. Magna magna sem, vel risus, mauris nunc purus. Ante in feugiat, sit phasellus suscipit, in mus facilisis. Tristique atque, erat et pede, lorem faucibus elit. Duis accumsan pulvinar.</p>
        </div>      
      </div>
    </div>
  </div>

  <!-- Twigs and Stems Modal -->
  <div tabindex="-1" class="modal fade" id="twigs-stemsbutton" role="dialog" aria-hidden="true" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button class="close" aria-label="Close" type="button" data-dismiss="modal"><span aria-hidden="true">×</span></button>
          <h4 class="modal-title"id="myModalLabel">Twigs and Stems</h4>
          <img src="#">
        </div>
        <div class="modal-body">
  				<p>Lorem ipsum dolor sit amet, faucibus libero ac. Purus tincidunt, eros amet eu, mattis ac sed. Tincidunt nibh vestibulum. Non magna, lobortis vestibulum, amet et. Mattis quis tincidunt, ut voluptatem. Non ligula nostra, suscipit in donec.

  				In nisl. Magna magna sem, vel risus, mauris nunc purus. Ante in feugiat, sit phasellus suscipit, in mus facilisis. Tristique atque, erat et pede, lorem faucibus elit. Duis accumsan pulvinar.</p>
        </div>      
      </div>
    </div>
  </div>

  <!-- General Modal -->
  <div tabindex="-1" class="modal fade" id="generalbutton" role="dialog" aria-hidden="true" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button class="close" aria-label="Close" type="button" data-dismiss="modal"><span  aria-hidden="true">×</span></button>
          <h4 class="modal-title" id="myModalLabel">General</h4>
          <img src="#">
        </div>
        <div class="modal-body">
          <p>Lorem ipsum dolor sit amet, faucibus libero ac. Purus tincidunt, eros amet eu, mattis ac sed. Tincidunt nibh vestibulum. Non magna, lobortis vestibulum, amet et. Mattis quis tincidunt, ut voluptatem. Non ligula nostra, suscipit in donec.

  				In nisl. Magna magna sem, vel risus, mauris nunc purus. Ante in feugiat, sit phasellus suscipit, in mus facilisis. Tristique atque, erat et pede, lorem faucibus elit. Duis accumsan pulvinar.</p>
        </div>      
      </div>
    </div>
  </div>
    
</div>  










</body>

app/views/pages/signup.html.erb
<div class="jumbotron center">
  <h1>Plant Website</h1>
  
  <% if user_signed_in? %>
    <% link_to "home" %>
  <% else %>
    <p>
      <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-lg" %>
    </p>
  <% end %>  
  
  <% if :destory_user_session %>
    <% link_to "home", root_path %>
  <% end %>  

</div>

app/views/pages/subscribe.html.erb


<div class="options">
	<div class="prices">
		<h1>$5/mo</h1>
	</div>
	<div class="benefits">
		<ul>benefits</ul>
			<li>benefit 1</li>
			<li>benefit 2</li>
			<li>benefit 3</li>
			<li>benefit 4</li>
	</div>
</div>

<div class="options">
	<div class="prices">
		<h1>$10/mo</h1>
	</div>
	<div class="benefits">
		<ul>benefits</ul>
			<li>benefit 1</li>
			<li>benefit 2</li>
			<li>benefit 3</li>
			<li>benefit 4</li>
	</div>
</div>

<div class="options">
	<div class="prices">
		<h1>$150/yr</h1>
	</div>
	<div class="benefits">
		<ul>benefits</ul>
			<li>benefit 1</li>
			<li>benefit 2</li>
			<li>benefit 3</li>
			<li>benefit 4</li>
	</div>
</div>